version: 0.1
log:
  level: debug # Options: debug, info, warn, error, fatal
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: false
      age: 168h
      interval: 24h
      dryrun: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
notifications:
  endpoints:
    - name: keel
      url: 'http://keel.k8s/v1/webhook/registry'
      headers:
        Content-Type: [application/json]
      timeout: '500ms'
      threshold: 5
      backoff: '1s'
      events:
        - push
